[pytest]
addopts = --numprocesses=2 --count=1 --dist=loadgroup --strict-markers --alluredir=allure-results/ --junitxml=report.xml
markers =
    xdist_group
    order
    smoke
    fast
    nightly
    negative
