name: API tests
on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:
  run-tests:
    runs-on: ubuntu-latest

    steps:
      - name: Check out repository
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.12.10'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Create config files
        run: |
          cat <<'EOF' > .settings.yaml
          ${{ env.SETTINGS_RAW }}
          EOF

          cat <<'EOF' > .secret.yaml
          ${{ env.SECRET_RAW }}
          EOF
        env:
          SETTINGS_RAW: ${{ secrets.SETTINGS_YAML }}
          SECRET_RAW: ${{ secrets.SECRET_YAML }}

      - name: Run API tests with pytest and generate Allure results
        continue-on-error: true
        run: |
          pytest --dist=loadgroup --strict-markers --env=test tests/ --numprocesses 2 --count 1 --alluredir=allure-results/ --junitxml=report.xml

      - name: Upload Allure results
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: allure-results
          path: allure-results/

  publish-report:
    if: always()
    needs: [ run-tests ]
    runs-on: ubuntu-latest

    permissions:
      contents: write
      pages: write
      id-token: write

    steps:
      - name: Download Allure results
        uses: actions/download-artifact@v4
        if: always()
        with:
          name: allure-results
          path: current-allure-results

      - name: Check out gh-pages branch
        uses: actions/checkout@v4
        if: always()
        continue-on-error: true
        with:
          ref: gh-pages
          path: gh-pages-dir

      - name: Set up Allure CLI
        if: always()
        run: |
          sudo apt-get update && sudo apt-get install -y wget unzip
          wget https://github.com
          unzip allure-2.32.0.zip
          sudo mv allure-2.32.0 /opt/allure
          sudo ln -s /opt/allure/bin/allure /usr/bin/allure

      - name: Generate Report and Clean History
        if: always()
        run: |
          # Створюємо структуру папок
          mkdir -p gh-pages-dir/allure-history
          mkdir -p gh-pages-dir/last-history
          
          if [ "$(ls -A gh-pages-dir/last-history 2>/dev/null)" ]; then
              mkdir -p current-allure-results/history
              cp -r gh-pages-dir/last-history/. current-allure-results/history/
          fi
          
          allure generate current-allure-results -o allure-report --clean
          
          mkdir -p gh-pages-dir/allure-history/${{ github.run_number }}
          cp -r allure-report/. gh-pages-dir/allure-history/${{ github.run_number }}/
          
          rm -rf gh-pages-dir/last-history/*
          cp -r allure-report/history/. gh-pages-dir/last-history/
          
          echo "<!DOCTYPE html><meta charset=\"utf-8\"><meta http-equiv=\"refresh\" content=\"0; URL=allure-history/${{ github.run_number }}/index.html\">" > gh-pages-dir/index.html
          
          ls -1d gh-pages-dir/allure-history/* | sort -n | head -n -20 | xargs rm -rf 2>/dev/null || true

      - name: Deploy to GitHub Pages
        if: always()
        uses: peaceiris/actions-gh-pages@v4
        with:
          github_token: ${{ secrets.ALLURE_TOKEN }}
          publish_branch: gh-pages
          publish_dir: gh-pages-dir